directories:
  # mirror_module_path: True
  output: "../docs"
  # raster_images: "/Users/grant/Dropbox/3Blue1Brown/images/raster"
  vector_images: "imgs"
  pi_creature_images: "imgs"
  # sounds: "/Users/grant/Dropbox/3Blue1Brown/sounds"
  # data: "/Users/grant/Dropbox/3Blue1Brown/data"
  # temporary_storage: ""
# universal_import_line: "from manim_imports_ext import *"
# tex:
#   executable: "xelatex -no-pdf"
#   template_file: "ctex_template.tex"
#   intermediate_filetype: "xdv"
style:
  font: "CMU Serif"
  background_color: "#000000"
camera_qualities:
  default_quality: "ultra_high"
window_position: UR
window_monitor: 1