name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt install ffmpeg
        sudo apt install texlive-latex-extra
        sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
        sudo apt install python3-setuptools
        pip3 install -r requirements.txt

    - name: Render
      run: |
        manimgl pi.py DefaultScene -i
        ls

  artifacts:
    needs: [build]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
