name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt install ffmpeg
        sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
        pip3 install --upgrade pip
        pip3 install manimgl

    - name: Render
      run: |
        manimgl pi.py DefaultScene -i
        ls